In [ ]:
import numpy as np
import scipy as sp
import scipy.linalg as linalg
import matplotlib.pyplot as plt

In [ ]:
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)

In [ ]:
# 10.i)
b[[1,0,1, 0],[0,1, 2, 0]] #Select elements(1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [ ]:
# 11.j)
b[[1,0,1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b[1,2]

6.0

In [ ]:
b[1]

array([4., 5., 6.])

In [ ]:
b[1][2]

6.0

In [ ]:
X = b[[1,0,1,0]]
X

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ]])

In [ ]:
X[[0,1, 2, 0]]

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [4. , 5. , 6. ]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
a[3]

4

In [ ]:
a[[3,7,9]]

array([ 4,  8, 10])

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
c[1,:,[2,0]]

array([[3, 6, 9],
       [1, 4, 7]])

In [ ]:
[c[i,j] for i,j in [(1,0),(2,2)]]

[4, 9]

In [ ]:
def f(x):
    return 2*x

In [ ]:
f(1)

2

In [ ]:
lambda x: 2*x

In [ ]:
g = lambda x: 2*x

In [ ]:
g(1)

2

In [ ]:
(lambda x: 2*x)(2)

4

In [1]:
import numpy as np

In [3]:
w = np.array([[1,2],[3,4]])

In [4]:
w

array([[1, 2],
       [3, 4]])

In [12]:
w[1,:]

array([3, 4])

In [13]:
a = np.array([3,4,5,6,4,7])

In [15]:
a[:]

array([3, 4, 5, 6, 4, 7])

In [17]:
n=10
k=5

In [18]:
(n,k+1)

(10, 6)

In [23]:
w = np.zeros([n,k+1])

In [24]:
w

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
for i in range(10):
    print(i)
    print("hola")
print(100)

0
hola
1
hola
2
hola
3
hola
4
hola
5
hola
6
hola
7
hola
8
hola
9
hola
100


In [30]:
def f(x):
    x=x+1
    print(x)
print(100)

100


In [33]:
f(50)
print(200)

51
200


In [ ]:
int f(x){
x = x+2
return x+1;
}

In [ ]:
y = f(200)