In [2]:
import numpy as np
import scipy as sp
import scipy.linalg as linalg
import matplotlib.pyplot as plt

In [5]:
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
a = np.matrix([1,2,3,4])
b = np.matrix([3,3,2,2])

In [12]:
c = np.array([1,2,3,4])
d = np.array([3,3,2,2])

In [11]:
a*b.T

matrix([[23]])

In [13]:
c*d

array([3, 6, 6, 8])

In [14]:
c*d.T

array([3, 6, 6, 8])